
title: Minhyuk Sung
url: 'http://cs.stanford.edu/~mhsung'
#baseurl: '/example' #change it according to your repository name

#Profile information
name: Minhyuk Sung
tagline: PhD Student<br>Computer Science<br>Stanford University
#pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: mhsung@cs.stanford.edu
website: cs.stanford.edu/~mhsung #do not add http://
linkedin: mhsung
github: mhsung
cv: www.dropbox.com/s/oxg78455trxx2or/cv.pdf?dl=1


# Tracker
analytics: UA-35688210-1
#Update all the sections by editing the files inside _includes folder.
